import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const sampleDialog = [
    { role: "user", message: "こんにちは" },
    { role: "assistant", message: "こんにちは。ご用件をお伝えください" },
    {
      role: "user",
      message: "GPTについて、小学生でも分かるように説明してください。",
    },
    {
      role: "assistant",
      message:
        "GPTとは、「Generative Pre-trained Transformer」の略称で、OpenAIが開発した人工知能の一種です。",
    },
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center h-screen">
        <div className="max-w-lg w-full">
          <div
            style={{ height: "650px" }}
            className="bg-gray-100 w-full p-4 h-96 overflow-scroll rounded-lg"
          >
            <span className="text-center block font-medium border-b-2 border-indigo-400 pb-4 mb-4">
              ChatGPT-Clone
            </span>
            {sampleDialog.map((dialog) =>
              dialog.role == "user" ? (
                <div className="flex justify-end mb-2">
                  <div className="bg-indigo-400 text-white p-2 rounded-md">
                    {dialog.message}
                  </div>
                </div>
              ) : (
                <div className="flex justify-start mb-2">
                  <div className="bg-gray-200 p-2 rounded-md">
                    {dialog.message}
                  </div>
                </div>
              )
            )}
          </div>
        </div>
      </div>
    </>
  );
}
